/**
 * SEO Constants - Keywords, anime titles, competitor terms for maximum search visibility
 * Targets: aniwatch, anilab, hianime + 200+ anime names + genre queries
 */

/** Competitor/alternative site terms - users search these when looking for anime streaming */
export const COMPETITOR_KEYWORDS = [
  'aniwatch',
  'anilab',
  'hianime',
  'aniwatch alternative',
  'anilab alternative',
  'hianime alternative',
  'watch anime like aniwatch',
  'anime site like anilab',
  'best anime streaming site',
  'free anime streaming',
  'anime watch online',
  'gogoanime',
  '9anime',
  'zoro',
  'animepahe',
  'crunchyroll alternative',
  'funimation alternative',
] as const;

/** 150+ popular anime titles - users search these directly */
export const POPULAR_ANIME_KEYWORDS = [
  'one piece',
  'naruto',
  'naruto shippuden',
  'jujutsu kaisen',
  'jjk',
  'demon slayer',
  'kimetsu no yaiba',
  'dragon ball',
  'dragon ball z',
  'dragon ball super',
  'attack on titan',
  'shingeki no kyojin',
  'bleach',
  'my hero academia',
  'bnha',
  'death note',
  'fullmetal alchemist',
  'fma brotherhood',
  'hunter x hunter',
  'hxh',
  'spy x family',
  'chainsaw man',
  'mob psycho',
  'one punch man',
  'opm',
  'solo leveling',
  'blue lock',
  'haikyu',
  'haikyuu',
  'kuroko no basket',
  'slam dunk',
  'black clover',
  'fairy tail',
  'sword art online',
  'sao',
  're zero',
  're:zero',
  'mushoku tensei',
  'jobless reincarnation',
  'that time i got reincarnated as a slime',
  'tensura',
  'overlord',
  'konosuba',
  'demon slayer movie',
  'jujutsu kaisen movie',
  'one piece film red',
  'dragon ball super broly',
  'your name',
  'makoto shinkai',
  'studio ghibli',
  'spirited away',
  'howl moving castle',
  'vinland saga',
  'berserk',
  'steins gate',
  'code geass',
  'evangelion',
  'neon genesis evangelion',
  'cowboy bebop',
  'samurai champloo',
  'trigun',
  'gintama',
  'jojo',
  'jojo bizarre adventure',
  'tokyo ghoul',
  'parasyte',
  'promised neverland',
  'dr stone',
  'fire force',
  'jujutsu kaisen season 2',
  'demon slayer season 4',
  'one piece episode',
  'boruto',
  'boruto naruto next generations',
  'dandadan',
  'frieren',
  'sousou no frieren',
  'classroom of the elite',
  'oregairu',
  'my teen romantic comedy',
  'kaguya sama',
  'love is war',
  'horimiya',
  'rent a girlfriend',
  'rent a girlfriend anime',
  'quintessential quintuplets',
  'gotoubun',
  'rent a girlfriend season',
  'demon slayer hashira training',
  'one piece egghead',
  'jjk season 3',
  'mha season 7',
  'bleach thousand year blood war',
  'tybw',
  'sakamoto days',
  'kaiju no 8',
  'delicious in dungeon',
  'dungeon meshi',
  'apothecary diaries',
  'oshi no ko',
  'bocchi the rock',
  'lycoris recoil',
  'cyberpunk edgerunners',
  'chainsaw man part 2',
  'jujutsu kaisen manga',
  'one piece manga',
  'anime sub',
  'anime dub',
  'anime sub indo',
  'anime english sub',
  'anime english dub',
] as const;

/** Brand keywords - helps rank for "anime village" (with space) */
export const BRAND_KEYWORDS = [
  'anime village',
  'anime village streaming',
  'anime village watch',
] as const;

/** Core streaming keywords */
export const CORE_KEYWORDS = [
  'anime',
  'watch anime',
  'anime streaming',
  'anime online',
  'anime online free',
  'stream anime',
  'anime episodes',
  'anime sub',
  'anime dub',
  'anime sub and dub',
  'free anime',
  'anime free',
  'watch anime free',
  'anime website',
  'anime site',
  'best anime site',
  'anime episodes online',
  'anime series',
  'anime movies',
  'anime tv',
] as const;

/** Genre keywords for genre pages */
export const GENRE_KEYWORDS = [
  'action anime',
  'romance anime',
  'comedy anime',
  'isekai anime',
  'shounen anime',
  'seinen anime',
  'fantasy anime',
  'sci-fi anime',
  'horror anime',
  'sports anime',
  'slice of life anime',
  'drama anime',
  'adventure anime',
  'mystery anime',
  'supernatural anime',
] as const;

/** Combined for meta keywords (max ~20-30 for best practice, but we use more for long-tail) */
export const ALL_SEO_KEYWORDS = [
  ...BRAND_KEYWORDS,
  ...CORE_KEYWORDS,
  ...COMPETITOR_KEYWORDS.slice(0, 6),
  ...POPULAR_ANIME_KEYWORDS.slice(0, 40),
] as const;
